### PR TITLE
Extract component api

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by metacosm** [comment]
See https://blog.jetbrains.com/go/2018/12/14/go-templates-made-easy/  for how to use go templates in IDEA

**Comment by cmoulliard** [comment]
Where can I find now the `API` vs `Internal `API` projects containing the fields to be used to configure either the API used with the user vs internal API used to configure the fields used by the operator to generate the k8s resources ? @metacosm

**Comment by metacosm** [comment]
> Where can I find now the `API` vs `Internal `API` projects containing the fields to be used to configure either the API used with the user vs internal API used to configure the fields used by the operator to generate the k8s resources ? @metacosm

The API is in a different project (github.com/snowdrop/component-api). The internal API is the same as before.

**Comment by metacosm** [comment]
Closed as obsolete. Will probably revisit at some point, though.

**Pull request closed without merging**
