### PR TITLE
WIP: Generic reconciler

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by cmoulliard** [comment]
When we execute this bash [script](https://github.com/snowdrop/component-operator-demo/blob/e253d5ddaf3d387a9bb35c2b3f38911d72db53a5/scripts/end-to-end_dummy_resources.sh) which deploys fruit-client, fruit-backend and DB

```
./scripts/end-to-end_dummy_resources.sh 195.201.87.126
```

against hetzner - namespace test1, we get this error

https://gist.github.com/cmoulliard/bbd7be72ca9e2082fb1a55ed5b3b63ad

**Comment by metacosm** [comment]
@cmoulliard should be fixed now

**Comment by cmoulliard** [comment]
If I try to deploy capability, ... then we got this error

```
2019-07-04T15:25:25.950+0200	INFO	cmd	Go Version: go1.12.4
2019-07-04T15:25:25.951+0200	INFO	cmd	Go OS/Arch: darwin/amd64
2019-07-04T15:25:25.951+0200	INFO	cmd	Version of operator-sdk: v0.7.0
2019-07-04T15:25:25.951+0200	INFO	cmd	component-operator version: Unset
2019-07-04T15:25:25.951+0200	INFO	cmd	component-operator git commit: HEAD
2019-07-04T15:25:25.951+0200	INFO	cmd	watching namespace test1
2019-07-04T15:25:26.064+0200	INFO	cmd	Registering Components
2019-07-04T15:25:26.064+0200	INFO	cmd	Registering 3rd party resources
2019-07-04T15:25:26.064+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "component-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "component-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "component-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "component-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "component-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "component-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "component-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "component-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "capability-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "capability-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.067+0200	INFO	kubebuilder.controller	Starting EventSource	{"controller": "link-controller", "source": "kind source: /, Kind="}
2019-07-04T15:25:26.171+0200	INFO	kubebuilder.controller	Starting Controller	{"controller": "capability-controller"}
2019-07-04T15:25:26.171+0200	INFO	kubebuilder.controller	Starting Controller	{"controller": "link-controller"}
2019-07-04T15:25:26.171+0200	INFO	kubebuilder.controller	Starting Controller	{"controller": "component-controller"}
2019-07-04T15:25:26.272+0200	INFO	kubebuilder.controller	Starting workers	{"controller": "capability-controller", "worker count": 1}
2019-07-04T15:25:26.276+0200	INFO	kubebuilder.controller	Starting workers	{"controller": "link-controller", "worker count": 1}
2019-07-04T15:25:26.276+0200	INFO	kubebuilder.controller	Starting workers	{"controller": "component-controller", "worker count": 1}
2019-07-04T15:25:31.618+0200	INFO	capability-controller	==> Reconciling Capability	{"name": "postgres-db", "status": "", "created": "2019-07-04 15:25:31 +0200 CEST"}
2019-07-04T15:25:31.618+0200	INFO	capability-controller	pod is not ready for component 'postgres-db' in namespace 'test1'
2019-07-04T15:25:31.618+0200	INFO	capability-controller	updating capability status	{"phase": "Pending", "podName": "", "message": "pod is not ready for component 'postgres-db' in namespace 'test1'"}
2019-07-04T15:25:31.733+0200	INFO	capability-controller	Created successfully	{"kind": "Secret"}
2019-07-04T15:25:31.747+0200	INFO	capability-controller	Created successfully	{"kind": "Postgres"}
2019-07-04T15:25:31.747+0200	INFO	capability-controller	<== Reconciled Capability	{"name": "postgres-db"}
E0704 15:25:31.747164    9081 runtime.go:67] Observed a panic: implement me
/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/runtime/runtime.go:76
/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/runtime/runtime.go:65
/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522
/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/capability/controller.go:88
/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:180
/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:250
/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:215
/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158
/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:152
/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:153
/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:88
/usr/local/Cellar/go/1.12.4/libexec/src/runtime/asm_amd64.s:1337
panic: implement me [recovered]
	panic: implement me

goroutine 295 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/runtime/runtime.go:58 +0x105
panic(0x20afce0, 0x35d2fb0)
	/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522 +0x1b5
github.com/snowdrop/component-operator/pkg/controller/capability.(*ReconcileCapability).SetSuccessStatus(0xc0000dc2e8, 0x3602020, 0xc0008e6ea0)
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/capability/controller.go:88 +0x39
github.com/snowdrop/component-operator/pkg/controller.(*BaseGenericReconciler).SetSuccessStatus(0xc0004e24e0, 0x3602020, 0xc0008e6ea0)
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:180 +0x53
github.com/snowdrop/component-operator/pkg/controller.(*BaseGenericReconciler).Reconcile(0xc0004e24e0, 0xc00090fe19, 0x5, 0xc00090fdf0, 0xb, 0x42e5600, 0x0, 0x0, 0x0)
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:250 +0x804
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000100820, 0x0)
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:215 +0x1cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158 +0x36
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000948050)
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:152 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000948050, 0x3b9aca00, 0x0, 0x1, 0xc0000b01e0)
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000948050, 0x3b9aca00, 0xc0000b01e0)
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:157 +0x311

Process finished with exit code 2
```

**Comment by cmoulliard** [comment]
This is perhaps not related to this PR change but we got this error 

```
2019-07-04T15:57:06.535+0200	INFO	component-controller	pod is not ready for component 'fruit-backend-sb' in namespace 'test'
2019-07-04T15:57:06.535+0200	INFO	component-controller	updating component status	{"phase": "Pending", "podName": "", "message": "pod is not ready for component 'fruit-backend-sb' in namespace 'test'"}
2019-07-04T15:57:06.553+0200	INFO	component-controller	==> Reconciling Component	{"name": "fruit-client-sb", "status": "Pending", "created": "2019-07-04 15:57:05 +0200 CEST"}
2019-07-04T15:57:06.608+0200	ERROR	component-controller	Failed to create new 	{"kind": "Route", "error": "routes.route.openshift.io \"fruit-client-sb\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/snowdrop/component-operator/pkg/controller.(*BaseGenericReconciler).CreateIfNeeded
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:319
github.com/snowdrop/component-operator/pkg/controller/component.(*ReconcileComponent).installDevMode
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/component/mode-dev.go:96
github.com/snowdrop/component-operator/pkg/controller/component.(*ReconcileComponent).CreateOrUpdate
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/component/controller.go:124
github.com/snowdrop/component-operator/pkg/controller.(*BaseGenericReconciler).CreateOrUpdate
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:172
github.com/snowdrop/component-operator/pkg/controller.(*BaseGenericReconciler).Reconcile
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:242
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:215
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:88
2019-07-04T15:57:06.608+0200	ERROR	component-controller	failed to create or update Component 'fruit-client-sb'	{"error": "routes.route.openshift.io \"fruit-client-sb\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/snowdrop/component-operator/pkg/controller.(*BaseGenericReconciler).Reconcile
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:244
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:215
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:88
2019-07-04T15:57:06.608+0200	INFO	component-controller	updating component status	{"phase": "Failed", "podName": "", "message": "routes.route.openshift.io \"fruit-client-sb\" already exists"}
2019-07-04T15:57:06.620+0200	ERROR	kubebuilder.controller	Reconciler error	{"controller": "component-controller", "request": "test/fruit-client-sb", "error": "routes.route.openshift.io \"fruit-client-sb\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:217
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:88
2019-07-04T15:57:06.692+0200	INFO	capability-controller	==> Reconciling Capability	{"name": "postgres-db", "status": "Pending", "created": "2019-07-04 15:56:34 +0200 CEST"}
2019-07-04T15:57:06.692+0200	INFO	capability-controller	<== Reconciled Capability	{"name": "postgres-db"}
```

**Comment by cmoulliard** [comment]
Error reported when the capability CR is deleted

```
2019-07-04T15:59:31.886+0200	ERROR	capability-controller	failed to update status for capability postgres-db	{"error": "Operation cannot be fulfilled on capabilities.devexp.runtime.redhat.com \"postgres-db\": StorageError: invalid object, Code: 4, Key: /openshift.io/devexp.runtime.redhat.com/capabilities/test/postgres-db, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 889a7178-9e63-11e9-af8c-080027577959, UID in object meta: "}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/snowdrop/component-operator/pkg/controller/capability.(*ReconcileCapability).updateStatusWithMessage
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/capability/status.go:34
github.com/snowdrop/component-operator/pkg/controller/capability.(*ReconcileCapability).makePending
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/capability/status.go:75
github.com/snowdrop/component-operator/pkg/controller/capability.(*ReconcileCapability).updateStatus
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/capability/status.go:58
github.com/snowdrop/component-operator/pkg/controller/capability.(*ReconcileCapability).SetSuccessStatus
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/capability/controller.go:90
github.com/snowdrop/component-operator/pkg/controller.(*BaseGenericReconciler).SetSuccessStatus
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:180
github.com/snowdrop/component-operator/pkg/controller.(*BaseGenericReconciler).Reconcile
	/Users/dabou/Code/go-workspace/src/github.com/snowdrop/component-operator/pkg/controller/generic.go:250
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:215
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/Users/dabou/Code/go-workspace/pkg/mod/sigs.k8s.io/controller-runtime@v0.1.9/pkg/internal/controller/controller.go:158
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/dabou/Code/go-workspace/pkg/mod/github.com/kmodules/apimachinery@v0.0.0-20190508045248-a52a97a7a2bf/pkg/util/wait/wait.go:88
```

**Pull request merged**
